# Ivory CKEditor
configs:
    minimal_config:
        toolbar: "minimal_toolbar"
        mediasBrowserRoute: {route: "minimal_manager_list", params: {module: "image"}}
        mediasBrowserThumbFormat: "medium"
        extraPlugins: "autogrow,dragresize,mediasbrowser"
        autoGrow_minHeight: 400
toolbars:
    configs:
        minimal_toolbar: [ "@document", "@clipboard", "@editing", "@tools", "/", "@basicstyles" , "@paragraph", "@links", "/", "@insert", "@styles", "@colors" ]
    items:
        document: [ "Source", "-" ]
        clipboard: [ "Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo" ]
        editing:     [ "Find","Replace","-","SelectAll","-" ]
        basicstyles:     [ "Bold","Italic","Underline","Strike","Subscript","Superscript","-","RemoveFormat" ]
        paragraph:     [ "NumberedList","BulletedList","-","Outdent","Indent","-","Blockquote","CreateDiv", "-","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock","-" ]
        links:     [ "Link","Unlink","Anchor" ]
        insert:     [ "Table","HorizontalRule","Smiley","SpecialChar" ]
        styles:     [ "Styles","Format","Font","FontSize" ]
        colors:     [ "TextColor","BGColor" ]
        tools:     [ "Maximize","ShowBlocks" ]
plugins:
    autogrow:
        path:     "/bundles/minimalmanager/js/ckeditor/plugins/autogrow/"
        filename: "plugin.js"
    dragresize:
        path:     "/bundles/minimalmanager/js/ckeditor/plugins/dragresize/"
        filename: "plugin.js"
